### ISSUE TITLE
find_gte but only return the index?

### ISSUE THREAD

**Issue by jguhlin** [jonhoo/ordsearch#30]
Is there currently a function to just return the index rather than the value for find_gte? Would be useful if not, can try a crack at it, but feel like it's there and I'm just missing it, haha.

**Comment by jonhoo** [comment]
That should be doable, although not sure why you're after it given that the order of the underlying memory is something that's managed directly by ordsearch?

cc @bazhenov

**Comment by jguhlin** [comment]
Ah, was hoping it'd be possible to convert to the original position easily,
no worries if not, disregard then.

**Comment by jonhoo** [comment]
You mean to convert it into the position in the original input? No, that's likely to be quite difficult :)

**Comment by jguhlin** [comment]
No worries, haha, worth a short. Cheers

**Comment by bazhenov** [comment]
> You mean to convert it into the position in the original input? No, that's likely to be quite difficult :)

FYI: when working on #18 one alternative I've tried was iterating not over input collection (and scattering elements to the eytzinger array), but iterating over the eytzinger array and gathering input elements. I wrote an algorithm that reverses eytzinger indices for that. I've trashed that code because the optimization didn't work out in the end, but it's definitely doable in log(N) time.
